function PostIt(b){this.postItDiv=document.createElement("div");this.postItDiv.className="postItDiv";this.pin=document.createElement("div");this.pin.className="pin";this.postItContent=document.createElement("p");this.postItContent.innerText=b;this.postItContent.className="postItContent";this.postItDiv.append(this.pin);this.postItDiv.append(this.postItContent);this.makeDraggable=function(){var a=!1,e,c;this.postItDiv.addEventListener("touchstart",function(d){a=!0;var m=d.touches[0];e=m.clientX-this.postItDiv.offsetLeft;
c=m.clientY-this.postItDiv.offsetTop;this.postItDiv.style.zIndex=Math.floor(Date.now()/1E3);d.preventDefault()}.bind(this));document.addEventListener("touchmove",function(d){a&&(d=d.touches[0],this.postItDiv.style.left=d.clientX-e+"px",this.postItDiv.style.top=d.clientY-c+"px")}.bind(this));document.addEventListener("touchend",function(){a=!1}.bind(this))}};function LowerMeny(){this.allPostIts=[];this.lowerHolder=document.getElementById("lowerHolder");this.board=document.getElementById("board");this.postItBtn=document.createElement("button");this.postItBtn.id="postItBtn";this.postItBtn.innerText="Ny post-it";this.lowerHolder.append(this.postItBtn);this.counter=document.createElement("p");this.counter.id="counter";this.lowerHolder.append(this.counter);this.trashCan=document.createElement("div");this.trashCan.id="trashCan";this.lowerHolder.append(this.trashCan);
this.loadSavedPostIts();this.updateCounter();this.postItMaker()}
LowerMeny.prototype.postItMaker=function(){var b=this.board.getBoundingClientRect();document.getElementById("postItBtn").addEventListener("click",function(){if(!document.getElementById("popupDiv")){var a=document.createElement("div");a.id="popupDiv";var e=document.createElement("form"),c=document.createElement("button");c.innerText="X";c.className="closePopUpBtn";c.setAttribute("type","button");var d=document.createElement("h1");d.innerText="Skapa en post it";d.id="postItH1";var m=document.createElement("label");
m.innerText="Skriv ett litet meddelande!";var h=document.createElement("textarea");h.setAttribute("type","text");h.setAttribute("rows",2);h.setAttribute("maxlength",25);var f=document.createElement("button");f.innerText="Spara";f.id="createBtn";f.setAttribute("type","button");a.style.zIndex=Math.floor(Date.now()/1E3);a.style.position="relative";e.append(c,d,m);m.append(h);a.append(e,f);document.body.append(a);f.addEventListener("click",function(){var k=h.value;if(""==k)alert("Du kanske ska testa att skriva n\u00e5got innan du f\u00f6rs\u00f6ker trycka p\u00e5 spara");
else{var l=new PostIt(k);l.makeDraggable();this.allPostIts.push(l);var g=Math.floor(Date.now()/1E3),n=Math.random()*(b.width-l.postItDiv.offsetWidth-160)+80,p=Math.random()*(b.height-l.postItDiv.offsetHeight-160)+80;l.postItDiv.style.position="absolute";l.postItDiv.style.left=n+"px";l.postItDiv.style.top=p+"px";this.saveToLocalStorage(g,k,n,p);this.board.append(l.postItDiv);a.remove();this.updateCounter()}}.bind(this));c.addEventListener("click",function(){a.remove();this.updateCounter()}.bind(this));
document.addEventListener("touchstart",function(k){a.contains(k.target)||k.target===this.postItBtn||a.remove()}.bind(this))}}.bind(this));this.movePostIt()};
LowerMeny.prototype.movePostIt=function(){document.addEventListener("touchstart",function(){for(var b=0;b<this.allPostIts.length;b++){var a=this.allPostIts[b];a.originalX=a.postItDiv.offsetLeft;a.originalY=a.postItDiv.offsetTop}}.bind(this));document.addEventListener("touchend",function(){for(var b=this.trashCan.getBoundingClientRect(),a=this.board.getBoundingClientRect(),e=0;e<this.allPostIts.length;e++){var c=this.allPostIts[e],d=c.postItDiv.getBoundingClientRect();if(!(d.right<b.left||d.left>b.right||
d.bottom<b.top||d.top>b.bottom)){this.trashCan.style.background="url(../img/\u00f6ppenSoptunna.svg)";this.trashCan.style.backgroundRepeat="no-repeat";setTimeout(()=>{this.trashCan.style.background="url(../img/st\u00e4ngdSoptunna.svg)";this.trashCan.style.backgroundRepeat="no-repeat"},1E3);this.removeFromLocalStorage(c.id);c.postItDiv.remove();this.allPostIts.splice(e,1);this.updateCounter();break}this.updatePosition(c);if(d.left<a.left||d.right>a.right||d.top<a.top||d.bottom>a.bottom){c.postItDiv.style.left=
c.originalX+"px";c.postItDiv.style.top=c.originalY+"px";this.updatePosition(c);break}}}.bind(this));this.wheatherHandler()};LowerMeny.prototype.updateCounter=function(){this.counter.innerText=this.allPostIts.length+"/20";this.postItBtn.disabled=20<=this.allPostIts.length?!0:!1};LowerMeny.prototype.saveToLocalStorage=function(b,a,e,c){var d=JSON.parse(localStorage.getItem("postIts"))||[];d.push({id:b,text:a,left:e,top:c});localStorage.setItem("postIts",JSON.stringify(d))};
LowerMeny.prototype.loadSavedPostIts=function(){for(var b=JSON.parse(localStorage.getItem("postIts"))||[],a=0;a<b.length;a++){var e=b[a],c=new PostIt(e.text);c.id=e.id;c.postItDiv.style.position="absolute";c.postItDiv.style.left=e.left+"px";c.postItDiv.style.top=e.top+"px";this.board.append(c.postItDiv);this.allPostIts.push(c);c.makeDraggable()}};
LowerMeny.prototype.removeFromLocalStorage=function(b){for(var a=JSON.parse(localStorage.getItem("postIts")),e=0;e<a.length;e++)if(a[e].id==b){a.splice(e,1);break}localStorage.setItem("postIts",JSON.stringify(a))};LowerMeny.prototype.updatePosition=function(b){for(var a=JSON.parse(localStorage.getItem("postIts")),e=0;e<a.length;e++)if(a[e].id==b.id){a[e].left=parseFloat(b.postItDiv.style.left);a[e].top=parseFloat(b.postItDiv.style.top);break}localStorage.setItem("postIts",JSON.stringify(a))};
LowerMeny.prototype.wheatherHandler=function(){var b=localStorage.getItem("wind"),a=localStorage.getItem("rain"),e=document.getElementById("holder");5<b&&(localStorage.clear(),e.style.background="rgb(104, 132, 143)",this.allPostIts=[],this.updateCounter());if(0<a)for(e.style.background="rgb(104, 132, 143)",b=0;b<this.allPostIts.length;b++)this.allPostIts[b].postItDiv.classList.add("rainyPost")};function UpperMeny(){this.upperHolder=document.getElementById("upperHolder");this.currentDiv=document.createElement("div");this.currentDiv.id="currentDiv";this.currentLocation=document.createElement("h1");this.currentLocation.innerText="Laddar";this.currentTemp=document.createElement("h1");this.currentTemp.innerText="...";this.upperHolder.append(this.currentDiv);this.currentDiv.append(this.currentLocation);this.currentDiv.append(this.currentTemp);"geolocation"in navigator?navigator.geolocation.getCurrentPosition(function(a){this.lat=
a.coords.latitude.toFixed(4);this.lon=a.coords.longitude.toFixed(4);this.fetchWheater(this.lat,this.lon)}.bind(this),function(a){a.code===a.PERMISSION_DENIED&&(alert("Om du inte till\u00e5ter att webbl\u00e4saren automatiskt hittar din plats kommer V\u00e4xj\u00f6 s\u00e4ttas, \u00e5ngrar du dig? Starta om sidan och till\u00e5t platsinformation"),this.lat=56.8776,this.lon=14.809,this.fetchWheater(this.lat,this.lon));a.code===a.POSITION_UNAVAILABLE&&alert("Ett fel intr\u00e4ffade n\u00e4r din position skulle h\u00e4mtas, testa att starta om webbl\u00e4saren")}.bind(this)):
alert("Geolocation st\u00f6ds inte i denna webbl\u00e4saren testa en annan webbl\u00e4sare om du vill anv\u00e4nda automatisk position");this.hamburgerMeny=document.createElement("div");this.hamburgerMeny.id="hamburgerMeny";for(var b=0;3>b;b++)this.bars=document.createElement("div"),this.bars.className="bars",this.hamburgerMeny.append(this.bars);this.upperHolder.append(this.hamburgerMeny);this.displayWheather()}
UpperMeny.prototype.fetchWheater=function(b,a){var e=`https://nominatim.openstreetmap.org/reverse?format=json&lat=${b}&lon=${a}`;fetch(`https://opendata-download-metfcst.smhi.se/api/category/pmp3g/version/2/geotype/point/lon/${a}/lat/${b}/data.json`).then(c=>c.json()).then(c=>{var d=c.timeSeries[0],m=d.parameters.find(g=>"t"==g.name).values[0];document.getElementById("sideMenyTemp").innerText=Math.round(m)+"\u00b0C";var h=d.parameters.find(g=>"ws"==g.name).values[0],f=d.parameters.find(g=>"pmean"==
g.name).values[0];d=d.parameters.find(g=>"tcc_mean"==g.name).values[0];localStorage.setItem("wind",h);localStorage.setItem("rain",f);5<h?(h="Det bl\u00e5ser",f=" och dina post-its har bl\u00e5sit bort",d="\ud83c\udf2a\ufe0f"):0<f?(h="Det regnar",f=" och dina post-its \u00e4r bl\u00f6ta",d="\ud83c\udf27\ufe0f"):4<d?(h="Det \u00e4r molnigt",f=" och dina post-its \u00e4r s\u00e4kra",d="\u2601\ufe0f"):(h="Det \u00e4r soligt",f=" och dina post-its \u00e4r s\u00e4kra",d="\u2600\ufe0f");document.getElementById("rainAndWind").innerText=
h+f;document.getElementById("wheatherImg").innerText=d;this.currentTemp.innerText=Math.round(m)+"\u00b0C"+d;document.getElementById("wheatherScroll").innerText="";for(f=0;10>f;f++){var k=c.timeSeries[f];m=(new Date(k.validTime)).getHours().toString().padStart(2,"0");h=k.parameters.find(g=>"t"==g.name).values[0];d=k.parameters.find(g=>"ws"==g.name).values[0];var l=k.parameters.find(g=>"pmean"==g.name).values[0];k=k.parameters.find(g=>"tcc_mean"==g.name).values[0];hourEmoji=5<d?"\ud83c\udf2a\ufe0f":
0<l?"\ud83c\udf27\ufe0f":4<k?"\u2601\ufe0f":"\u2600\ufe0f";d=document.createElement("div");d.className="wheatherBoxs";l=document.createElement("div");l.className="wheatherDivs";l.innerText=m+":00 "+Math.round(h)+"\u00b0C "+hourEmoji;document.getElementById("wheatherScroll").append(d);d.append(l)}}).catch(c=>console.error(c));fetch(e).then(c=>c.json()).then(c=>{this.currentLocation.innerHTML=c?c.address.city||c.adress.county||c.adress.country:"Ok\u00e4nd plats"}).catch(c=>console.error(c))};
UpperMeny.prototype.displayWheather=function(){var b=document.createElement("div");b.id="sideMeny";b.style.display="none";document.body.append(b);this.hamburgerMeny.addEventListener("click",function(){b.style.display="block"});document.addEventListener("touchstart",function(e){b.contains(e.target)||e.target===document.getElementById("hamburgerMeny")||(b.style.display="none",b.style.zIndex=Math.floor(Date.now()/1E3))});var a=document.createElement("button");a.id="back";a.innerText="X";b.append(a);
a.addEventListener("click",function(){b.style.display="none"});a=document.createElement("div");a.id="wheatherImg";b.append(a);a=document.createElement("div");a.id="sideMenyTemp";b.append(a);a=document.createElement("div");a.id="rainAndWind";b.append(a);a=document.createElement("div");a.id="wheatherScroll";b.append(a)};function Main(){new LowerMeny;new UpperMeny}window.addEventListener("load",function(){new Main});
