function PostIt(b){this.postItDiv=document.createElement("div");this.postItDiv.className="postItDiv";this.pin=document.createElement("div");this.pin.className="pin";this.postItContent=document.createElement("p");this.postItContent.textContent=b;this.postItContent.className="postItContent";this.postItDiv.appendChild(this.pin);this.postItDiv.appendChild(this.postItContent);this.makeDraggable=function(){var a=!1,c,d;this.postItDiv.addEventListener("mousedown",function(e){a=!0;c=e.clientX-this.postItDiv.offsetLeft;
d=e.clientY-this.postItDiv.offsetTop;this.postItDiv.style.zIndex=Math.floor(Date.now()/1E3)}.bind(this));document.addEventListener("mousemove",function(e){a&&(this.postItDiv.style.position="absolute",this.postItDiv.style.left=e.clientX-c+"px",this.postItDiv.style.top=e.clientY-d+"px")}.bind(this));document.addEventListener("mouseup",function(){a=!1}.bind(this))}};function LowerMeny(){this.allPostIts=[];this.lowerHolder=document.getElementById("lowerHolder");this.board=document.getElementById("board");this.postItBtn=document.createElement("button");this.postItBtn.id="postItBtn";this.postItBtn.innerHTML="Ny post-it";this.lowerHolder.appendChild(this.postItBtn);this.counter=document.createElement("p");this.counter.id="counter";this.lowerHolder.appendChild(this.counter);this.trashCan=document.createElement("div");this.trashCan.id="trashCan";this.lowerHolder.appendChild(this.trashCan);
this.loadSavedPostIts();this.updateCounter();this.postItMaker()}
LowerMeny.prototype.postItMaker=function(){document.getElementById("postItBtn").addEventListener("click",function(){if(!document.getElementById("popupDiv")){var b=document.createElement("div");b.id="popupDiv";var a=document.createElement("form"),c=document.createElement("button");c.innerHTML="X";c.className="closePopUpBtn";c.setAttribute("type","button");var d=document.createElement("h1");d.innerHTML="Skapa en post it";d.id="postItH1";var e=document.createElement("label");e.innerHTML="Skriv ett litet meddelande!";
var f=document.createElement("textarea");f.setAttribute("type","text");f.setAttribute("rows",2);f.setAttribute("maxlength",25);var h=document.createElement("button");h.innerHTML="Spara";h.id="createBtn";h.setAttribute("type","button");b.style.zIndex=Math.floor(Date.now()/1E3);b.style.position="relative";a.append(c,d,e);e.appendChild(f);b.append(a,h);document.body.append(b);h.addEventListener("click",function(){var l=f.value;if(""==l)alert("Du kanske ska testa att skriva n\u00e5got innan du f\u00f6rs\u00f6ker trycka p\u00e5 spara");
else{var k=new PostIt(l);k.makeDraggable();this.allPostIts.push(k);var m=Math.floor(Date.now()/1E3);k.id=m;var g=this.board.getBoundingClientRect(),n=Math.random()*(g.width-k.postItDiv.offsetWidth);g=Math.random()*(g.height-k.postItDiv.offsetHeight);k.postItDiv.style.position="absolute";k.postItDiv.style.left=n+"px";k.postItDiv.style.top=g+"px";this.saveToLocalStorage(m,l,n,g);this.board.appendChild(k.postItDiv);b.remove();this.updateCounter()}}.bind(this));c.addEventListener("click",function(){b.remove();
this.updateCounter()}.bind(this));document.addEventListener("mousedown",function(l){b.contains(l.target)||l.target===this.postItBtn||b.remove()}.bind(this))}}.bind(this));this.movePostIt()};
LowerMeny.prototype.movePostIt=function(){var b,a;document.addEventListener("mousedown",function(){for(var c=0;c<this.allPostIts.length;c++){var d=this.allPostIts[c];b=d.postItDiv.offsetLeft;a=d.postItDiv.offsetTop}}.bind(this));document.addEventListener("mouseup",function(){for(var c=this.trashCan.getBoundingClientRect(),d=this.board.getBoundingClientRect(),e=0;e<this.allPostIts.length;e++){var f=this.allPostIts[e],h=f.postItDiv.getBoundingClientRect();if(this.elementsAreOverlapping(h,c)){this.removeFromLocalStorage(f.id);
f.postItDiv.remove();this.allPostIts.splice(e,1);this.updateCounter();break}this.updatePosition(f);if(!this.elementsAreOverlapping(h,d)){f.postItDiv.style.left=b+"px";f.postItDiv.style.top=a+"px";this.updatePosition(f);break}}}.bind(this));this.wheatherHandler()};LowerMeny.prototype.updateCounter=function(){this.counter.innerHTML=this.allPostIts.length+"/20";this.postItBtn.disabled=20<=this.allPostIts.length?!0:!1};
LowerMeny.prototype.elementsAreOverlapping=function(b,a){return!(b.right<a.left||b.left>a.right||b.bottom<a.top||b.top>a.bottom)};LowerMeny.prototype.saveToLocalStorage=function(b,a,c,d){var e=JSON.parse(localStorage.getItem("postIts"))||[];e.push({id:b,text:a,left:c,top:d});localStorage.setItem("postIts",JSON.stringify(e))};
LowerMeny.prototype.loadSavedPostIts=function(){for(var b=JSON.parse(localStorage.getItem("postIts"))||[],a=0;a<b.length;a++){var c=b[a],d=new PostIt(c.text);d.id=c.id;d.postItDiv.style.position="absolute";d.postItDiv.style.left=c.left+"px";d.postItDiv.style.top=c.top+"px";this.board.appendChild(d.postItDiv);this.allPostIts.push(d);d.makeDraggable()}};
LowerMeny.prototype.removeFromLocalStorage=function(b){for(var a=JSON.parse(localStorage.getItem("postIts")),c=0;c<a.length;c++)if(a[c].id==b){a.splice(c,1);break}localStorage.setItem("postIts",JSON.stringify(a))};LowerMeny.prototype.updatePosition=function(b){for(var a=JSON.parse(localStorage.getItem("postIts")),c=0;c<a.length;c++)if(a[c].id==b.id){a[c].left=parseFloat(b.postItDiv.style.left);a[c].top=parseFloat(b.postItDiv.style.top);break}localStorage.setItem("postIts",JSON.stringify(a))};
LowerMeny.prototype.wheatherHandler=function(){document.getElementById("holder")};function UpperMeny(){this.upperHolder=document.getElementById("upperHolder");this.currentDiv=document.createElement("div");this.currentDiv.id="currentDiv";this.currentLocation=document.createElement("h1");this.currentLocation.innerHTML="Laddar";this.currentTemp=document.createElement("h1");this.currentTemp.innerHTML="...";this.upperHolder.appendChild(this.currentDiv);this.currentDiv.appendChild(this.currentLocation);this.currentDiv.appendChild(this.currentTemp);"geolocation"in navigator?navigator.geolocation.getCurrentPosition(function(a){this.lat=
a.coords.latitude.toFixed(4);this.lon=a.coords.longitude.toFixed(4);this.fetchWheater(this.lat,this.lon)}.bind(this),function(a){a.code===a.PERMISSION_DENIED&&(alert("Om du inte till\u00e5ter att webbl\u00e4saren automatiskt hittar din plats kommer V\u00e4xj\u00f6 s\u00e4ttas, \u00e5ngrar du dig? Starta om sidan och till\u00e5t platsinformation"),this.lat=56.8776,this.lon=14.809,this.fetchWheater(this.lat,this.lon))}.bind(this)):alert("Geolocation st\u00f6ds inte i denna webbl\u00e4saren testa en annan webbl\u00e4sare om du vill anv\u00e4nda automatisk position");
this.hamburgerMeny=document.createElement("div");this.hamburgerMeny.id="hamburgerMeny";for(var b=0;3>b;b++)this.bars=document.createElement("div"),this.bars.className="bars",this.hamburgerMeny.append(this.bars);this.upperHolder.appendChild(this.hamburgerMeny);this.displayWheather();this.hamburgerMeny.addEventListener("click",function(){sideMeny.classList.toggle("active")})}
UpperMeny.prototype.fetchWheater=function(b,a){var c=`https://nominatim.openstreetmap.org/reverse?format=json&lat=${b}&lon=${a}`;fetch(`https://opendata-download-metfcst.smhi.se/api/category/pmp3g/version/2/geotype/point/lon/${a}/lat/${b}/data.json`).then(d=>d.json()).then(d=>{var e=d.timeSeries[0],f=e.parameters.find(g=>"t"==g.name).values[0];this.currentTemp.innerHTML=Math.round(f)+"\u00b0C";document.getElementById("sideMenyTemp").innerHTML=Math.round(f)+"\u00b0C";f=e.parameters.find(g=>"ws"==g.name).values[0];
var h=e.parameters.find(g=>"pmean"==g.name).values[0];e=e.parameters.find(g=>"tcc_mean"==g.name).values[0];localStorage.setItem("wind",f);localStorage.setItem("rain",h);5<f?(e="Det bl\u00e5ser",f=" och dina post-its har bl\u00e5sit bort",h="\ud83c\udf2a\ufe0f"):0<h?(e="Det regnar",f=" och dina post-its \u00e4r bl\u00f6ta",h="\ud83c\udf27\ufe0f"):4<e?(e="Det \u00e4r molnigt",f=" och dina post-its \u00e4r s\u00e4kra",h="\u2601\ufe0f"):(e="Det \u00e4r soligt",f=" och dina post-its \u00e4r s\u00e4kra",
h="\u2600\ufe0f");document.getElementById("rainAndWind").textContent=e+f;document.getElementById("wheatherImg").textContent=h;document.getElementById("wheatherScroll").textContent="";for(h=0;10>h;h++){var l=d.timeSeries[h];e=(new Date(l.validTime)).getHours().toString().padStart(2,"0");f=l.parameters.find(g=>"t"==g.name).values[0];var k=l.parameters.find(g=>"ws"==g.name).values[0],m=l.parameters.find(g=>"pmean"==g.name).values[0];l=l.parameters.find(g=>"tcc_mean"==g.name).values[0];hourEmoji=5<k?
"\ud83c\udf2a\ufe0f":0<m?"\ud83c\udf27\ufe0f":4<l?"\u2601\ufe0f":"\u2600\ufe0f";k=document.createElement("div");k.className="wheatherBoxs";m=document.createElement("div");m.className="wheatherDivs";m.textContent=e+":00 "+Math.round(f)+"\u00b0C "+hourEmoji;document.getElementById("wheatherScroll").appendChild(k);k.appendChild(m)}}).catch(d=>console.error(d));fetch(c).then(d=>d.json()).then(d=>{d?this.currentLocation.innerHTML=d.address.city||d.adress.county||d.adress.country:this.currentLocation.textContent=
"Ok\u00e4nd plats"}).catch(d=>console.error(d))};
UpperMeny.prototype.displayWheather=function(){var b=document.createElement("div");document.body.appendChild(b);b.id="sideMeny";document.addEventListener("click",function(c){b.contains(c.target)||c.target===document.getElementById("hamburgerMeny")||b.classList.remove("active")});var a=document.createElement("button");a.id="back";a.textContent="X";b.appendChild(a);a.addEventListener("click",function(c){b.classList.removeChild("active")});a=document.createElement("div");a.id="wheatherImg";b.appendChild(a);
a=document.createElement("div");a.id="sideMenyTemp";b.appendChild(a);a=document.createElement("div");a.id="rainAndWind";b.appendChild(a);a=document.createElement("div");a.id="wheatherScroll";b.appendChild(a)};function Main(){new LowerMeny;new UpperMeny}window.addEventListener("load",function(){new Main});
